export const CATALOGUE = [
  {
    code: "Finex 1",
    name: "ETF Finex FXTB",
    salesPoints: "IE00BL3DYW26  - гособлигации США с защитой от инфляции",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "13.48%",
    risk: "85%",
    expirationDate: "",
    minAmount: "736.4",
    currency: "RUB",
    step: "736.4",
    price: 736.4,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "2.00%",
  },
  {
    code: "Finex 2",
    name: "ETF Finex FXWO",
    salesPoints: "IE00BK224L29 - акции глобального рынка",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "39.24%",
    risk: "75%",
    expirationDate: "",
    minAmount: "1815",
    currency: "RUB",
    step: "1815",
    price: 1815,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "2.50%",
  },
  {
    code: "БПИФ",
    name: "Биржевой фонд «Открытие — Всепогодный»",
    salesPoints:
      "Стратегия фонда предполагает размещение средств в 5 иностранных инвестиционных фондов (ETF), инвестирующих в крупнейшие акции и облигации компаний США, золото, недвижимость США и акции компаний развивающихся стран.",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "8.00%",
    risk: "75%",
    expirationDate: "",
    minAmount: "1000",
    currency: "RUB",
    step: "1000",
    price: 1000,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "2.50%",
  },
  {
    code: "САМИТ N",
    name: "Акции российских эмитентов",
    salesPoints:
      "Компания - Тикер (Потенциал роста)\nАФК Система - AFKS (45%)\nGlobaltrans - GLTR (30,2%)\nРусагро - AGRO (22,3%)\nPetropavlovsk - POG (56,3%)\nРусал - RUAL (21,1%)\nСбербанк - SBER (0%)\nМТС - MTSS (5%)\nГК Самолет - SMLT (3,1%)",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "22.97%",
    risk: "60%",
    expirationDate: "",
    minAmount: "5000",
    currency: "RUB",
    step: "5000",
    price: 5000,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "1.80%",
  },
  {
    code: "СПБ N",
    name: "Акции иностранных эмитентов (SPB exchange)",
    salesPoints:
      "Компания - Тикер (Потенциал роста)\nApple Inc - AAPL (5%)\nMicrosoft Corp - MSFT (5,2%)\nVisa Inc - V (6,7%)\nIntel Corp - INTC (22,2%)\nIntuit Inc - INTU (5,6%)\nMerck & Co Inc - MRK (27,4%)\nMedtronic PLC - MDT (-6,5%)\nVertex Pharmaceuticals Inc - VRTX (19,2%)\nAmazon.com Inc - AMZN (19,3%)\nNIKE Inc - NKE (1,8%)",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "18.60%",
    risk: "75%",
    expirationDate: "",
    minAmount: "1000",
    currency: "USD",
    step: "10",
    price: 1000,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "1.80%",
  },
  {
    code: "ПИФ 1",
    name: "ПИФ «Открытие — Облигации»",
    salesPoints:
      "Инвестиции в государственные облигации, облигации субъектов РФ и долговые обязательства компаний, по большей части номинированные в рублях, и банковские депозиты. Сильная диверсификация по отраслям и компаниям позволяет снизить волатильность стоимости пая. Фонд нацелен на превышение ставки по рублевым депозитам в среднесрочной перспективе.",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "6.00%",
    risk: "90%",
    expirationDate: "",
    minAmount: "5000",
    currency: "RUB",
    step: "5000",
    price: 1,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "3.00%",
  },
  {
    code: "ПИФ 2",
    name: "ПИФ «Открытие — Акции» ",
    salesPoints:
      "Инвестиционная стратегия фонда предполагает активное управление, базирующееся на принципах долгосрочного инвестирования, диверсификации и эффективного риск-менеджмента. Инвестирование осуществляется преимущественно в недооцененные акции «первого» эшелона и наиболее перспективные акции «второго» эшелона с высоким потенциалом роста в долгосрочной перспективе.",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "15.00%",
    risk: "85%",
    expirationDate: "",
    minAmount: "5000",
    currency: "RUB",
    step: "5000",
    price: 1,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "3.00%",
  },
  {
    code: "КОРП",
    name: "Корпоративные облигации",
    salesPoints: "#ERROR!",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "8.60%",
    risk: "82%",
    expirationDate: "",
    minAmount: "10000",
    currency: "RUB",
    step: "1000",
    price: 1,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "1.50%",
  },
  {
    code: "ДУ СП",
    name: "Структурный продукт в оболочке ДУ",
    salesPoints: "Новый продукт! ",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "20.00%",
    risk: "60%",
    expirationDate: "",
    minAmount: "100000",
    currency: "RUB",
    step: "100000",
    price: 1,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "4.00%",
  },
  {
    code: "GLD",
    name: "Золото ",
    salesPoints:
      "Золото - вечный актив. Хранение в драгоценных металах - надежное решение для долгосрочной защиты вашего капитала. \nНет платы за хранение золота! Доходность за 2020 год составила 48%.",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "8.00%",
    risk: "68%",
    expirationDate: "",
    minAmount: "50,000  ",
    currency: "RUB",
    step: "50000",
    price: 1,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "1.50%",
  },
  {
    code: "ЗПИФ",
    name: "Закрытый паевой фонд",
    salesPoints: "",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "14%",
    risk: "65%",
    expirationDate: "",
    minAmount: "6,000,000  ",
    currency: "RUB",
    step: "1",
    price: 1,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "3.00%",
  },
  {
    code: "СП",
    name: "Структурный продукт",
    salesPoints:
      "Структурный продукт позволяет спланировать получение дохода в случае отcутствия существенного падения акций входящих в корзину.\nСостав портфеля:\nAFLT_HYDR_MGNT_SBERP",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "20%",
    risk: "60%",
    expirationDate: "",
    minAmount: "  250,000   ",
    currency: "RUB",
    step: "1",
    price: 1,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "6.00%",
  },
  {
    code: "EO",
    name: "Еврооблигация",
    salesPoints: "Sovcombank PERP - XS2113968148 - 7,72%",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "13%",
    risk: "65%",
    expirationDate: "",
    minAmount: "  10,000,000   ",
    currency: "RUB",
    step: "  10,000,000   ",
    price: 1,
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "1.50%",
  },
];
